
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.

module "global-lb-frontend" {
  source        = "github.com/terraform-google-modules/terraform-google-lb-http//modules/frontend?ref=v14.2.0"
  name          = "global-lb-frontend"
  project_id    = "qwiklabs-asl-01-964394115550"
  url_map_input = module.global-lb-backend.backend_service_info
  depends_on    = [module.project-services-qwiklabs-asl-01-964394115550, module.project-services-billing-project]
}
module "global-lb-backend" {
  source     = "github.com/terraform-google-modules/terraform-google-lb-http//modules/backend?ref=v13.2.0"
  name       = "global-lb-backend"
  project_id = "qwiklabs-asl-01-964394115550"
  serverless_neg_backends = [{
    region          = module.api-gateway-cloud-run.location
    service_name    = module.api-gateway-cloud-run.service_name
    service_version = ""
    type            = "cloud-run"
  }]
  security_policy = "projects/qwiklabs-asl-01-964394115550/global/securityPolicies/my-cloud-armor-policy"
  depends_on      = [module.project-services-qwiklabs-asl-01-964394115550, module.project-services-billing-project]
}
module "api-gateway-cloud-run" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.23.0"
  project_id                    = "qwiklabs-asl-01-964394115550"
  location                      = "us-central1"
  service_name                  = "api-gateway-cloud-run"
  containers                    = [{"container_image" = "us-central1-docker.pkg.dev/qwiklabs-asl-01-964394115550/my-repo/api-gateway:latest", "container_name" = "service-container", "env_vars" = merge({"onboarding_agent_cloud_run_SERVICE_ENDPOINT" = module.onboarding-agent-cloud-run.service_uri}, {"content_creator_agent_cloud_run_SERVICE_ENDPOINT" = module.content-creator-agent-cloud-run.service_uri}, {"integration_analysis_agent_cloud_run_SERVICE_ENDPOINT" = module.integration-analysis-agent-cloud-run.service_uri}, {"a2a_agent_1_SERVICE_ENDPOINT" = module.a2a-agent-1.service_uri}, {"a2a_agent_2_SERVICE_ENDPOINT" = module.a2a-agent-2.service_uri}, {"instagram_connector_cloud_run_SERVICE_ENDPOINT" = module.instagram-connector-cloud-run.service_uri}), "ports" = {"container_port" = 8080}}]
  gpu_zonal_redundancy_disabled = false
  service_account_project_roles = concat(["roles/run.invoker"], ["roles/run.invoker"], ["roles/run.invoker"], ["roles/run.invoker"], ["roles/run.invoker"], ["roles/run.invoker"])
  ingress                       = "INGRESS_TRAFFIC_INTERNAL_LOAD_BALANCER"
  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  service_scaling = {
    min_instance_count = 0
  }
  template_scaling = {
    min_instance_count = 0
  }
  depends_on = [module.project-services-qwiklabs-asl-01-964394115550, module.project-services-billing-project]
}
module "onboarding-agent-cloud-run" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.23.0"
  project_id                    = "qwiklabs-asl-01-964394115550"
  location                      = "us-central1"
  service_name                  = "onboarding-agent-cloud-run"
  containers                    = [{"container_image" = "us-central1-docker.pkg.dev/qwiklabs-asl-01-964394115550/my-repo/onboarding-agent:latest", "container_name" = "service-container", "env_vars" = {"legal_agent_cloud_run_SERVICE_ENDPOINT" = module.legal-agent-cloud-run.service_uri}, "ports" = {"container_port" = 8080}}]
  gpu_zonal_redundancy_disabled = false
  service_account_project_roles = ["roles/run.invoker"]
  ingress                       = "INGRESS_TRAFFIC_INTERNAL_LOAD_BALANCER"
  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  service_scaling = {
    min_instance_count = 0
  }
  template_scaling = {
    min_instance_count = 0
  }
  depends_on = [module.project-services-qwiklabs-asl-01-964394115550, module.project-services-billing-project]
}
module "content-creator-agent-cloud-run" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.23.0"
  project_id                    = "qwiklabs-asl-01-964394115550"
  location                      = "us-central1"
  service_name                  = "content-creator-agent-cloud-run"
  containers                    = [{"container_image" = "us-central1-docker.pkg.dev/qwiklabs-asl-01-964394115550/my-repo/content-creator-agent:latest", "container_name" = "service-container", "ports" = {"container_port" = 8080}}]
  gpu_zonal_redundancy_disabled = false
  ingress                       = "INGRESS_TRAFFIC_INTERNAL_LOAD_BALANCER"
  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  service_scaling = {
    min_instance_count = 0
  }
  template_scaling = {
    min_instance_count = 0
  }
  depends_on = [module.project-services-qwiklabs-asl-01-964394115550, module.project-services-billing-project]
}
module "integration-analysis-agent-cloud-run" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.23.0"
  project_id                    = "qwiklabs-asl-01-964394115550"
  location                      = "us-central1"
  service_name                  = "integration-analysis-agent-cloud-run"
  containers                    = [{"container_image" = "us-central1-docker.pkg.dev/qwiklabs-asl-01-964394115550/my-repo/integration-analysis-agent:latest", "container_name" = "service-container", "ports" = {"container_port" = 8080}}]
  gpu_zonal_redundancy_disabled = false
  ingress                       = "INGRESS_TRAFFIC_INTERNAL_LOAD_BALANCER"
  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  service_scaling = {
    min_instance_count = 0
  }
  template_scaling = {
    min_instance_count = 0
  }
  depends_on = [module.project-services-qwiklabs-asl-01-964394115550, module.project-services-billing-project]
}
module "a2a-agent-1" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.23.0"
  project_id                    = "qwiklabs-asl-01-964394115550"
  location                      = "us-central1"
  service_name                  = "a2a-agent-1"
  containers                    = [{"container_image" = "us-central1-docker.pkg.dev/qwiklabs-asl-01-964394115550/my-repo/a2a-agent-1:latest", "container_name" = "service-container", "ports" = {"container_port" = 8080}}]
  gpu_zonal_redundancy_disabled = false
  service_account_project_roles = ["roles/aiplatform.user"]
  ingress                       = "INGRESS_TRAFFIC_INTERNAL_LOAD_BALANCER"
  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  service_scaling = {
    min_instance_count = 0
  }
  service_labels = {
    vertex_ai_vertex-ai = "true"
  }
  template_scaling = {
    min_instance_count = 0
  }
  depends_on = [module.project-services-qwiklabs-asl-01-964394115550, module.project-services-billing-project]
}
module "a2a-agent-2" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.23.0"
  project_id                    = "qwiklabs-asl-01-964394115550"
  location                      = "us-central1"
  service_name                  = "a2a-agent-2"
  containers                    = [{"container_image" = "us-central1-docker.pkg.dev/qwiklabs-asl-01-964394115550/my-repo/a2a-agent-2:latest", "container_name" = "service-container", "ports" = {"container_port" = 8080}}]
  gpu_zonal_redundancy_disabled = false
  service_account_project_roles = ["roles/aiplatform.user"]
  ingress                       = "INGRESS_TRAFFIC_INTERNAL_LOAD_BALANCER"
  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  service_scaling = {
    min_instance_count = 0
  }
  service_labels = {
    vertex_ai_vertex-ai = "true"
  }
  template_scaling = {
    min_instance_count = 0
  }
  depends_on = [module.project-services-qwiklabs-asl-01-964394115550, module.project-services-billing-project]
}
module "vertex-ai" {
  source        = "github.com/terraform-google-modules/terraform-google-project-factory//modules/project_services?ref=v18.0.0"
  project_id    = "qwiklabs-asl-01-964394115550"
  activate_apis = ["aiplatform.googleapis.com"]
  depends_on    = [module.project-services-qwiklabs-asl-01-964394115550, module.project-services-billing-project]
}
module "instagram-connector-cloud-run" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.23.0"
  project_id                    = "qwiklabs-asl-01-964394115550"
  location                      = "us-central1"
  service_name                  = "instagram-connector-cloud-run"
  containers                    = [{"ports" = {"container_port" = 8080}, "container_image" = "us-central1-docker.pkg.dev/qwiklabs-asl-01-964394115550/my-repo/instagram-connector:latest", "container_name" = "service-container", "env_secret_vars" = {"secret_manager_SECRET" = module.secret-manager.env_vars.SECRET}}]
  gpu_zonal_redundancy_disabled = false
  service_account_project_roles = ["roles/secretmanager.secretAccessor"]
  ingress                       = "INGRESS_TRAFFIC_INTERNAL_LOAD_BALANCER"
  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  service_scaling = {
    min_instance_count = 0
  }
  template_scaling = {
    min_instance_count = 0
  }
  depends_on = [module.project-services-qwiklabs-asl-01-964394115550, module.project-services-billing-project]
}
module "secret-manager" {
  source      = "github.com/GoogleCloudPlatform/terraform-google-secret-manager//modules/simple-secret?ref=v0.9.0"
  project_id  = "qwiklabs-asl-01-964394115550"
  name        = "my-secret"
  secret_data = "my-secret-value"
  depends_on  = [module.project-services-qwiklabs-asl-01-964394115550, module.project-services-billing-project]
}
module "legal-agent-cloud-run" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.23.0"
  project_id                    = "qwiklabs-asl-01-964394115550"
  location                      = "us-central1"
  service_name                  = "legal-agent-cloud-run"
  containers                    = [{"container_name" = "service-container", "ports" = {"container_port" = 8080}, "container_image" = "us-central1-docker.pkg.dev/qwiklabs-asl-01-964394115550/my-repo/legal-agent:latest"}]
  gpu_zonal_redundancy_disabled = false
  service_account_project_roles = ["roles/aiplatform.user"]
  ingress                       = "INGRESS_TRAFFIC_INTERNAL_LOAD_BALANCER"
  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  service_scaling = {
    min_instance_count = 0
  }
  service_labels = {
    vertex_ai_vertex-ai = "true"
  }
  template_scaling = {
    min_instance_count = 0
  }
  depends_on = [module.project-services-qwiklabs-asl-01-964394115550, module.project-services-billing-project]
}
module "apphub" {
  source         = "github.com/GoogleCloudPlatform/terraform-google-apphub?ref=v0.4.0"
  project_id     = var.apphub_project_id
  location       = var.apphub_location
  service_uris   = concat(module.global-lb-frontend.apphub_service_uri, module.global-lb-backend.apphub_service_uri, [module.api-gateway-cloud-run.apphub_service_uri], [module.onboarding-agent-cloud-run.apphub_service_uri], [module.content-creator-agent-cloud-run.apphub_service_uri], [module.integration-analysis-agent-cloud-run.apphub_service_uri], [module.a2a-agent-1.apphub_service_uri], [module.a2a-agent-2.apphub_service_uri], [module.instagram-connector-cloud-run.apphub_service_uri], [module.legal-agent-cloud-run.apphub_service_uri])
  application_id = var.apphub_application_id
}
module "project-services-qwiklabs-asl-01-964394115550" {
  source                      = "github.com/terraform-google-modules/terraform-google-project-factory//modules/project_services?ref=v18.2.0"
  project_id                  = "qwiklabs-asl-01-964394115550"
  disable_services_on_destroy = false
  activate_apis               = ["accesscontextmanager.googleapis.com", "admin.googleapis.com", "appengine.googleapis.com", "billingbudgets.googleapis.com", "certificatemanager.googleapis.com", "cloudbilling.googleapis.com", "cloudkms.googleapis.com", "cloudresourcemanager.googleapis.com", "compute.googleapis.com", "essentialcontacts.googleapis.com", "iam.googleapis.com", "iamcredentials.googleapis.com", "iap.googleapis.com", "monitoring.googleapis.com", "oslogin.googleapis.com", "pubsub.googleapis.com", "run.googleapis.com", "secretmanager.googleapis.com", "serviceconsumermanagement.googleapis.com", "serviceusage.googleapis.com", "storage-api.googleapis.com", "vpcaccess.googleapis.com"]
}
module "project-services-billing-project" {
  source                      = "github.com/terraform-google-modules/terraform-google-project-factory//modules/project_services?ref=v18.2.0"
  project_id                  = "qwiklabs-asl-01-964394115550"
  disable_services_on_destroy = false
  activate_apis               = ["accesscontextmanager.googleapis.com", "admin.googleapis.com", "appengine.googleapis.com", "apphub.googleapis.com", "billingbudgets.googleapis.com", "certificatemanager.googleapis.com", "cloudbilling.googleapis.com", "cloudkms.googleapis.com", "cloudresourcemanager.googleapis.com", "compute.googleapis.com", "essentialcontacts.googleapis.com", "iam.googleapis.com", "iamcredentials.googleapis.com", "iap.googleapis.com", "monitoring.googleapis.com", "oslogin.googleapis.com", "pubsub.googleapis.com", "run.googleapis.com", "secretmanager.googleapis.com", "serviceconsumermanagement.googleapis.com", "serviceusage.googleapis.com", "storage-api.googleapis.com", "vpcaccess.googleapis.com"]
}
