
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.

output "global-lb-frontend_external_ip" {
  description = "The external IPv4 assigned to the global fowarding rule."
  value       = module.global-lb-frontend.external_ip
}
output "global-lb-frontend_external_ipv6_address" {
  description = "The external IPv6 assigned to the global fowarding rule."
  value       = module.global-lb-frontend.external_ipv6_address
}
output "global-lb-frontend_ip_address_internal_managed_http" {
  description = "The internal/external IP addresses assigned to the HTTP forwarding rules."
  value       = module.global-lb-frontend.ip_address_internal_managed_http
}
output "global-lb-frontend_ip_address_internal_managed_https" {
  description = "The internal/external IP addresses assigned to the HTTPS forwarding rules."
  value       = module.global-lb-frontend.ip_address_internal_managed_https
}
output "api-gateway-cloud-run_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.api-gateway-cloud-run.service_uri
}
output "onboarding-agent-cloud-run_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.onboarding-agent-cloud-run.service_uri
}
output "content-creator-agent-cloud-run_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.content-creator-agent-cloud-run.service_uri
}
output "integration-analysis-agent-cloud-run_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.integration-analysis-agent-cloud-run.service_uri
}
output "a2a-agent-1_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.a2a-agent-1.service_uri
}
output "a2a-agent-2_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.a2a-agent-2.service_uri
}
output "instagram-connector-cloud-run_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.instagram-connector-cloud-run.service_uri
}
output "legal-agent-cloud-run_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.legal-agent-cloud-run.service_uri
}
